### PR TITLE
ML model about everythings that I could do.

### PR DESCRIPTION
**Pull request by Yue-Fu1**
This train.ipynp is the way to Manufacture PKL files. The ml.py stores the method that app_ml.py need to use. Except predicting for a certain hour, I also write the function to get the StandsAvailable for an average time and predict for a day, which might be helpful

### CODE REVIEW

**Comment by AprilPolubiec** [comment]
something seems off in the notebook:

Mean Squared Error for station 1: 0.0
Mean Squared Error for station 2: 0.0
Mean Squared Error for station 3: 0.0
Mean Squared Error for station 4: 0.0
Mean Squared Error for station 5: 0.0
Mean Squared Error for station 6: 0.0
Mean Squared Error for station 7: 0.0
Mean Squared Error for station 8: 0.0
Mean Squared Error for station 9: 0.0
Mean Squared Error for station 10: 0.0
Mean Squared Error for station 11: 0.0

Shouldn't the mse be greater than 0? If its 0 that means the prediction was exactly correct which seems unlikely

**Comment by Yue-Fu1** [comment]
> something seems off in the notebook:
> 
> Mean Squared Error for station 1: 0.0 Mean Squared Error for station 2: 0.0 Mean Squared Error for station 3: 0.0 Mean Squared Error for station 4: 0.0 Mean Squared Error for station 5: 0.0 Mean Squared Error for station 6: 0.0 Mean Squared Error for station 7: 0.0 Mean Squared Error for station 8: 0.0 Mean Squared Error for station 9: 0.0 Mean Squared Error for station 10: 0.0 Mean Squared Error for station 11: 0.0
> 
> Shouldn't the mse be greater than 0? If its 0 that means the prediction was exactly correct which seems unlikely

Because the available bikes data you give are all equal.

**Comment by Yue-Fu1** [comment]
> > something seems off in the notebook:
> > Mean Squared Error for station 1: 0.0 Mean Squared Error for station 2: 0.0 Mean Squared Error for station 3: 0.0 Mean Squared Error for station 4: 0.0 Mean Squared Error for station 5: 0.0 Mean Squared Error for station 6: 0.0 Mean Squared Error for station 7: 0.0 Mean Squared Error for station 8: 0.0 Mean Squared Error for station 9: 0.0 Mean Squared Error for station 10: 0.0 Mean Squared Error for station 11: 0.0
> > Shouldn't the mse be greater than 0? If its 0 that means the prediction was exactly correct which seems unlikely
> 
> Because the available bikes data you give are all equal.

We have to collect data with enough fluctuation to get reliable pkl.

**Comment by AprilPolubiec** [comment]
closing this - i pulled your work into my branch

**Pull request closed without merging**
